import os

replacements = {
    "'Beranda'": "'Home'",
    "'Menemukan'": "'Discover'",
    "'Keuangan'": "'Finance'",
    "'Komputer'": "'Computer'",
    "'Penghubung'": "'Connectors'",
    "'File'": "'Files'",
    "'Contoh Langsung'": "'Live Examples'",
    "'Perpustakaan'": "'Library'",
    "'Ruang'": "'Spaces'",
    "'Riwayat'": "'History'",
    "'Tanyakan apa saja...'": "'Ask anything...'",
    "'Pilih Tindakan'": "'Choose Action'",
    "'Unggah File'": "'Upload File'",
    "'Pilih Gambar'": "'Choose Image'",
    "'Kamera'": "'Camera'",
    "'Fitur belum tersedia'": "'Feature not available yet'",
    "'Dibuat oleh'": "'Created by'",
    "'(Anda)'": "'(You)'",
    "'vulgansara7908 (Anda)'": "'vulgansara7908 (You)'",
    "'Terakhir Diperbarui'": "'Last Updated'",
    "'Hari ini'": "'Today'",
    "'Tambahkan Penanda'": "'Add Bookmark'",
    "'Tambahkan ke Space'": "'Add to Space'",
    "'Ubah Nama Thread'": "'Rename Thread'",
    "'Ekspor sebagai PDF'": "'Export as PDF'",
    "'Ekspor sebagai Markdown'": "'Export as Markdown'",
    "'Ekspor sebagai DOCX'": "'Export as DOCX'",
    "'Hapus'": "'Delete'",
    "'Bagikan utas ini'": "'Share this thread'",
    "'Privat'": "'Private'",
    "'Hanya penulis yang dapat melihat'": "'Only the author can view'",
    "'Siapa pun dengan tautan'": "'Anyone with the link'",
    "'Tautan disalin. Tempel untuk dibagikan'": "'Link copied. Paste to share'",
    "'Bagikan'": "'Share'",
    "'Pilih paket Anda'": "'Choose your plan'",
    "'Tingkatkan untuk pengalaman penelusuran yang lebih luas dan model AI premium.'": "'Upgrade for a broader search experience and premium AI models.'",
    "'Pribadi'": "'Personal'",
    "'Pendidikan'": "'Education'",
    "'Bisnis'": "'Business'",
    "'Populer'": "'Popular'",
    "'Jawaban lanjutan dan model AI terbaik'": "'Advanced answers and best AI models'",
    "'/bulan atau setara, saat ditagih tahunan'": "'/month or equivalent, billed annually'",
    "'Semua yang ada di Gratis dan:'": "'Everything in Free, plus:'",
    "'Akses ke model AI terbaru, yang telah dilatih pasca untuk akurasi yang lebih tinggi'": "'Access to latest AI models, post-trained for higher accuracy'",
    "'Pilih antara GPT-5.2, Gemini 3.1 Pro, Grok 4.1, dan lainnya'": "'Choose between GPT-5.2, Gemini 3.1 Pro, Grok 4.1, and more'",
    "'Lebih baik untuk pertanyaan kompleks dan membuat laporan, dokumen, dan aplikasi'": "'Better for complex questions and creating reports, documents, and apps'",
    "'Sumber yang lebih dalam dari indeks Perplexity, termasuk data keuangan dan ilmiah'": "'Deeper sources from Perplexity index, including financial and scientific data'",
    "'Dapatkan Pro'": "'Get Pro'",
    "'Dapatkan akses ke model AI terbaik'": "'Get access to the best AI models'",
    "'Baru'": "'New'",
    "'Maks'": "'Max'",
    "'Dihost di Amerika Serikat'": "'Hosted in the United States'",
    "'Apa yang ingin Anda ketahui?'": "'What do you want to know?'",
    "'Pengaturan'": "'Settings'",
    "'Ubah Profil'": "'Edit Profile'",
    "'AKUN'": "'ACCOUNT'",
    "'Berlangganan'": "'Subscription'",
    "'Gratis'": "'Free'",
    "'Tema'": "'Theme'",
    "'Gelap'": "'Dark'",
    "'Bahasa'": "'Language'",
    "'Indonesia'": "'English'",
    "'TENTANG'": "'ABOUT'",
    "'Bantuan & Dukungan'": "'Help & Support'",
    "'Kebijakan Privasi'": "'Privacy Policy'",
    "'Ketentuan Layanan'": "'Terms of Service'",
    "'Keluar'": "'Log Out'",
    "'Thread Baru'": "'New Thread'",
    "'Aplikasi'": "'Apps'",
    "'Dokumen'": "'Documents'",
    "'Cari thread Anda...'": "'Search your threads...'",
    "'Ketikan'": "'Type'",
    "'Thread Sementara: Tampilkan'": "'Temporary Threads: Show'",
    "'Urutkan: Terbaru'": "'Sort by: Newest'",
    "'menit yang lalu'": "'mins ago'",
    "'Templat'": "'Templates'",
    "'Undangan'": "'Invitations'",
    "'Ruang Saya'": "'My Spaces'",
    "'Contoh'": "'Examples'",
    "'Dibagikan'": "'Shared'",
    "'Jawaban'": "'Answer'",
    "'Tautan'": "'Links'",
    "'Gambar-gambar'": "'Images'",
    "'Ditinjau 10 sumber >'": "'Reviewed 10 sources >'",
    "'Mencari informasi saham Indonesia terbaru.'": "'Searching for latest Indonesian stock information.'",
    "'Sedang mencari'": "'Searching'",
    "'Meninjau sumber'": "'Reviewing sources'",
    "'Komputer berfungsi.'": "'Computer is active.'",
    "'Apa pun yang bisa dilakukan AI, Daemon Computer bisa melakukannya untuk Anda.'": "'Anything AI can do, Daemon Computer can do for you.'",
    "'Apa yang harus kita kerjakan selanjutnya?'": "'What should we work on next?'",
    "'Untuk menggunakan Computer,\\nAnda memerlukan paket Max'": "'To use Computer,\\nyou need the Max plan'",
    "'Tingkatkan'": "'Upgrade'",
    "'Contoh tugas'": "'Example tasks'",
    "'Kocok'": "'Shuffle'",
    "'Buat peringkat senyawa anti-penuaan menggunakan data ITP dan...'": "'Rank anti-aging compounds using ITP data and...'",
    "'Buat slide kuliah persamaan diferensial tingkat perguruan tinggi yang mencakup...'": "'Create college-level differential equations lecture slides covering...'",
    "'Buat aplikasi web mobile untuk protokol latihan kekuatan Huberman, lengkap...'": "'Build a mobile web app for Huberman\\'s strength training protocol, complete...'",
    "'Cari ticker...'": "'Search ticker...'",
    "'Pasar AS'": "'US Markets'",
    "'Kripto'": "'Crypto'",
    "'Pendapatan'": "'Earnings'",
    "'Prediksi'": "'Predictions'",
    "'Screener'": "'Screener'",
    "'Pergerakan Indeks'": "'Index Movements'",
    "'Sentimen Bearish'": "'Bearish Sentiment'",
    "'Ringkasan Pasar'": "'Market Summary'",
    "'Diperbarui 1 menit yang lalu'": "'Updated 1 min ago'",
    "'Pasar ditutup lebih rendah minggu ini dipimpin oleh penurunan sektor teknologi'": "'Markets closed lower this week led by tech sector decline'",
    "'Saham-saham AS sebagian besar ditutup lebih rendah pada hari Jumat, dengan NASDAQ memimpin penurunan karena sektor teknologi mengalami aksi jual...'": "'US stocks mostly closed lower on Friday, with NASDAQ leading the decline as the tech sector experienced a sell-off...'",
    "'Fokus tertuju pada data inflasi PCE minggu depan'": "'Focus turns to PCE inflation data next week'",
    "'Tanyakan apa pun tentang pasar AS'": "'Ask anything about US markets'",
    "'Daemon dapat melakukan sinkronisasi dengan alat harian Anda secara berurutan,\\nmemberikan kemampuan untuk menanggapi dengan menggunakan informasi secara real-time.'": "'Daemon can sync with your daily tools seamlessly,\\ngiving it the ability to respond using real-time information.'",
    "'Email dari Google'": "'Email from Google'",
    "'Email & Kalender dari Microsoft'": "'Email & Calendar from Microsoft'",
    "'Otomatisasi Pemasaran & CRM'": "'Marketing Automation & CRM'",
    "'Perangkat SEO Terpadu'": "'All-in-one SEO Toolset'",
    "'Platform untuk membangun database kolaboratif'": "'Platform for building collaborative databases'",
    "'Platform intelijen untuk penjualan'": "'Sales intelligence platform'",
    "'CRM untuk generasi modern'": "'CRM for the modern generation'",
    "'Aktifkan'": "'Enable'",
    "'Cari file'": "'Search files'",
    "'Belum ada file.'": "'No files yet.'",
    "'Mulai tugas komputer untuk membuat file.'": "'Start a computer task to create files.'",
    "'Tugas Komputer Baru'": "'New Computer Task'",
    "'Selesai'": "'Completed'",
    "'Menganalisis pendanaan pemegang saham OpenAI...'": "'Analyzing OpenAI shareholder funding...'",
    "'Menulis skrip Python untuk analisis data log harian...'": "'Writing Python script for daily log data analysis...'",
    "'Mencari artikel terkait inovasi AI di tahun 2026...'": "'Searching for articles related to AI innovations in 2026...'",
    "'Menunggu...'": "'Waiting...'",
    "'Membaca repositori github untuk dokumentasi flutter...'": "'Reading github repository for flutter documentation...'",
    "'Semua kategori'": "'All categories'",
    "'Konektor belum dapat diaktifkan'": "'Connector cannot be enabled yet'",
    "'Fitur pencarian belum tersedia'": "'Search feature not available yet'",
    "'Cari konektor'": "'Search connectors'",
    "'Cari file belum tersedia'": "'Search file not available yet'",
    "'Status'": "'Status'",
    "'Tugas'": "'Task'",
}


def process_file(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    original_content = content
    for indo, eng in replacements.items():
        content = content.replace(indo, eng)

    if content != original_content:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Updated: {filepath}")


for root, dirs, files in os.walk("lib"):
    for file in files:
        if file.endswith(".dart"):
            process_file(os.path.join(root, file))

print("Translation complete.")
